/*
 * Builds the assistant's knowledge base: data/knowledge/*.md → api/_kb.js
 * Every "## heading" becomes one chunk; title, heading and tags are weighted for search.
 * BM25 statistics are precomputed so a serverless cold start does no indexing work.
 * Run: npm run kb (also runs before every build).
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tokens } from "../api/_text.js";

const root = join(dirname(fileURLToPath(import.meta.url)), ".."), dir = join(root, "data/knowledge");
const chunks = [];
for (const file of readdirSync(dir).filter(f => f.endsWith(".md") && f !== "README.md").sort()) {
    const raw = readFileSync(join(dir, file), "utf8").replace(/\r\n/g, "\n");
    const fm = raw.match(/^---\n([\s\S]*?)\n---\n/), meta = {};
    (fm?.[1] || "").split("\n").forEach(l => { const i = l.indexOf(":"); if (i > 0) meta[l.slice(0, i).trim()] = l.slice(i + 1).trim(); });
    const body = fm ? raw.slice(fm[0].length) : raw;
    const title = meta.title || file.replace(/\.md$/, ""), tags = meta.tags || "";
    for (const part of body.split(/^## /m).map(s => s.trim()).filter(Boolean)) {
        const nl = part.indexOf("\n"), section = (nl < 0 ? part : part.slice(0, nl)).trim(), text = (nl < 0 ? "" : part.slice(nl + 1)).replace(/\s+/g, " ").trim();
        if (!text) continue;
        // field weights: tags ×3, section heading ×2, title ×1, body ×1
        const toks = [...tokens(tags), ...tokens(tags), ...tokens(tags), ...tokens(section), ...tokens(section), ...tokens(title), ...tokens(text)];
        const tf = {}; toks.forEach(t => { tf[t] = (tf[t] || 0) + 1; });
        chunks.push({ id: `${file.replace(/\.md$/, "")}#${chunks.length}`, file, title, section, text, len: toks.length, tf });
    }
}
if (!chunks.length) throw new Error("knowledge base is empty");
const df = {}; chunks.forEach(c => Object.keys(c.tf).forEach(t => { df[t] = (df[t] || 0) + 1; }));
const avgdl = chunks.reduce((s, c) => s + c.len, 0) / chunks.length;
const out = `/* GENERATED by scripts/build-kb.mjs from data/knowledge/*.md. Do not edit by hand. */\nexport const KB = ${JSON.stringify({ built: new Date().toISOString(), N: chunks.length, avgdl, df, chunks })};\n`;
writeFileSync(join(root, "api/_kb.js"), out);
console.log(`knowledge base: ${chunks.length} chunks from ${new Set(chunks.map(c => c.file)).size} files → api/_kb.js`);
